### ISSUE TITLE
How to retrieve the mappability file for hg38

### ISSUE THREAD

**Issue by emiTsukuba** [ZijieJin/scFusion#1]
Hi, I'm interested in scFusion and would like to run it on hg38.
Would you kindly tell me how to retrieve the mappability file for hg38?
I guess that I could retrieve it with UCSC Table browser by the following steps, is it right?

- assembly: hg38
- group: Mapping and Sequencing
- track: Umap
- table: Umap S24
- output format: BED

**Comment by ZijieJin** [comment]
Yes, This is the right step. I have downloaded the mappability file and found its format was different from hg19's. Thus, I recommend you modifying the file you downloaded to match the format of hg19's.

**Comment by emiTsukuba** [comment]
Thank you so much for quick reply!

I believe that the format of hg19 is as follows;

track type=wiggle_0 name="CRG Align 75" description="Alignability of 75mers by GEM from ENCODE/CRG(Guigo)"
#bedGraph section chr1:10000-74532
chr1	10000	10039	0.00218818
chr1	10039	10040	0.125
:

So I should select chrom, chromStart, chromEnd, and score for hg38 as follows, is it OK?

#chrom	chromStart	chromEnd	score
chr1	10158	10181	1
chr1	10599	10645	1
:

**Comment by ZijieJin** [comment]
Right!

**Comment by emiTsukuba** [comment]
I got it! Thanks!!

**Comment by ZijieJin** [comment]
Welcome~~
