### ISSUE TITLE
% of mapped reads very low (due to 88 % of reads being too short to be mapped)

### ISSUE THREAD

**Issue by jcostea** [ZijieJin/scFusion#10]
Hi,
I am currently trying to run the Testdata set. It's running all the way through but still does not provide a final fusion candidate (Result.abridged.txt, Result.full.txt are empty). When checking the STAR Mapping humanLog.final.out I realised that 88% of the reads are too short to be mapped (to the hg38 genome) and the average mapping is around 10 % (please see image below).

<img width="504" alt="image" src="https://user-images.githubusercontent.com/87424288/173820895-a82b9b63-0ae0-4471-aad1-c9514a1e1ea5.png">

Could you please provide me some guidance?
Please let me know if you need more information.

Many thanks for your help!

Best wishes,
Julia

**Comment by ZijieJin** [comment]
It is 10X data right? scFusion is optimized for Smart-Seq data, and the read length should >100 bp in pair.

**Comment by jcostea** [comment]
Hi, thanks for the fast reply! No I actually am using your provided Testdata set.

**Comment by ZijieJin** [comment]
It seems strange. Other users tried the test data and reported the expected results. Could you try mapping using reference hg19?

**Comment by jcostea** [comment]
When using  the hg19 genome the mappability is much higher, thanks! (although I don't really understand why). Nethertheless, the result file is still empty. I am attaching the output.txt of my run. Many thanks for your help!

<img width="454" alt="image" src="https://user-images.githubusercontent.com/87424288/173864835-5736662a-74d6-4ddd-bec7-b989c70d9911.png">

[output.txt](https://github.com/ZijieJin/scFusion/files/8910804/output.txt)

**Comment by ZijieJin** [comment]
In line 254 of the output.txt, it says "2022-06-15 17:12:04.589877: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory"

The dynamic library was not installed properly. Try fix it!

**Comment by jcostea** [comment]
thanks. The problem is identified. it seems to be a problem of my conda as everything worked when I tried it with the conda environment of a colleague. We will try to fix it internally. Many thanks for your help!
