### ISSUE TITLE
Is this tool human-specific?

### ISSUE THREAD

**Issue by 14zac2** [ZijieJin/scFusion#11]
Hello!

I am considering trying scFusion on 10X droplet-based scRNA-seq reads using data from an obscure model organism. Right now I am identifying fusions using Arriba. I saw in a closed issue that running your tool on 10X data may lead to missed fusions, but I am also wondering if it is possible to run on non-human data? I have a custom-made GTF and FASTA file.

Many thanks,
Zoe

**Comment by ZijieJin** [comment]
10X data is not good for gene fusion detection, due to the short read length and low coverage. scFusion can be applied to non-human data, but when using 10X data, the performance might not be good
