### ISSUE TITLE
Some thing wrong with RmLowMappibility_ChimericRead_NoFilter.py ?

### ISSUE THREAD

**Issue by cx994** [ZijieJin/scFusion#12]
When use RmLowMappibility_ChimericRead_NoFilter.py to  process file generated by testdata （humanChimeric.out.sam generated by 10_1.fastq and 10_2.fastq)，I got the empty .sam file .

**Comment by ZijieJin** [comment]
Oooops. It was a bug. The next version will come out asap to fix it.

**Comment by cx994** [comment]
So ... Can I finish `ReadProcessing` progress whithout mappability filter now?

**Comment by ZijieJin** [comment]
Check the new version now

**Comment by cx994** [comment]
ohhhhhhhh,thanks.I will try it again!!

**Comment by cx994** [comment]
Hi,Jin.I found I can't find fusion candidates of the testdata(10_1.fastq,10_2.fastq) use the `FusionCandidate`.Is there still some bug in the software？
![image](https://user-images.githubusercontent.com/81349137/177237479-f2ff62a9-11d4-4e3b-8bb8-16f3f3ddf6e8.png)

**Comment by ZijieJin** [comment]
email me with your wechat id to talk more.

**Comment by ZijieJin** [comment]
Start over and see the result
