### ISSUE TITLE
PreProcessing_SingleFile.py

### ISSUE THREAD

**Issue by zmbiolab** [ZijieJin/scFusion#15]
Traceback (most recent call last):
  File "/usr/local/src/scFusion/bin/PreProcessing_SingleFile.py", line 50, in <module>
    Data1[index,:,0] = np.array([int(c) for c in ChimericRead[index].upper().replace('A','0').replace('T','1').replace('C','2').replace('G','3').replace('H','4')])
ValueError: could not broadcast input array from shape (16,) into shape (61,)

**Comment by ZijieJin** [comment]
Hey! First check whether the data is Smart-seq2 or 10X. scFusion requires the long reads as input (>=60bp)

**Comment by zmbiolab** [comment]
> Hey! First check whether the data is Smart-seq2 or 10X. scFusion requires the long reads as input (>=60bp)

Thank you!
