### ISSUE TITLE
Input Fastq File Origin

### ISSUE THREAD

**Issue by Keyan719** [ZijieJin/scFusion#17]
Thanks so much for providing this amazing package. It is stated that the input fastq is from Smart-seq. I wonder if this tool is also compatible with the output fastq files from 10X protocol? If so, could there be any suggestions to solve the conflict? Thanks once again.

**Comment by ZijieJin** [comment]
Due to the low sequencing quality of 10X protocol, scFusion might not detect gene fusions or have low sensitivity. I do not recommend you applying scFusion to 10X data.
