### ISSUE TITLE
SMART-seq2 with read length less than 60 bp

### ISSUE THREAD

**Issue by cbiagii** [ZijieJin/scFusion#18]
First of all, thank you so much for such a comprehensive and helpful pipeline!

I'm trying to run on the data I have (SMART-seq2) and I'm having problems in the FusionCandidate step.
My samples have reads with a length of 38 bp, so when I get to the FusionCandidate step I get the error below:
_ValueError: could not broadcast input array from shape (39,) into shape (61,)_

I would like to know if you have any suggestions for running scFusion in this case, where my reads are smaller than 60 bp but are SMART-seq.

Thank you very much for your help!

**Comment by ZijieJin** [comment]
I do not recommend you applying scFusion to this dataset. The read is too short to detect gene fusions, or the sensitivity might be very low

**Comment by cbiagii** [comment]
Thanks a lot for you reply!
