### ISSUE TITLE
function cannot be evaluated at initial parameters

### ISSUE THREAD

**Issue by Tcooler** [ZijieJin/scFusion#19]
Hellow,
     I run the FusionReport but get the error that:
''
     Error in optim(rnorm(9, mean = -0.4, sd = 0.1), CalcZINB, control = list(maxit = 10000)) : 
  function cannot be evaluated at initial parameters
''
   I don't know how to set the initial parameters, can you help me?
   Thanks

**Comment by ZijieJin** [comment]
Please run the pipeline again. If the problem still exists, the data may not fit the model.
