### ISSUE TITLE
How to prepare the mappability and weight files for mm10?

### ISSUE THREAD

**Issue by RongDing-NMU** [ZijieJin/scFusion#20]
Hello,

Thanks for this useful package! I'm working on single cell fusion analysis and would like to run scFusion on mm10. But I'm a little confused about the optional files. Are the mappability file and weight file necessary? Can you tell me tell me how to prepare the mm10 mappability file? And whether the scFusion/data/weight-V9-2.hdf5 file is still suitable for mm10?

Thanks.

**Comment by ZijieJin** [comment]
The mappability file is not necessary. The weight file stores the pre-trained parameters, and you can safely apply it to mm10 datasets. (But I do not recommend it when the species is not human or mouse)
