### ISSUE TITLE
Will the pipeline support 10X bam files?

### ISSUE THREAD

**Issue by jwweii** [ZijieJin/scFusion#21]
Hi Zijie,

Thanks for this useful package! I am wondering will the pipeline support 10X bam files in the future? If not, could I just modify the STAR arguments to align with the needs of 10X bam file and then continue your pipeline?

Thanks,
Evan

**Comment by ZijieJin** [comment]
Hi Evan, 

10X data is not suitable for detecting gene fusions, so I do not recommend you modifying the pipeline. For detecting gene fusions, please use bulk sequencing data or Smart-seq data.
