### ISSUE TITLE
Inquiry about scFusion Tool Compatibility with DNA Normal Samples and FusionReport Error

### ISSUE THREAD

**Issue by AnkitYGeneSeq** [ZijieJin/scFusion#22]
**Tool Compatibility with DNA Normal Samples:**
I am currently testing the scFusion tool for analyzing DNA samples. I have encountered a couple of issues that I would like to bring to your attention

**Error in Generating FusionReport with Testdata:**
While testing the tool using the provided test data **samples,** I encountered an error when attempting to generate the FusionReport. I am using a single sample for testing, and the error message I received is as follows:

```
Error in read.table(Args[8], sep = "\t", stringsAsFactors = F) :
  no lines available in input
Execution halted
Traceback (most recent call last):
  File ".//bin//TidyupFusionFinalResult.py", line 25, in <module>
    ResultFile = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: 'testdata_out//FinalResult/temp/Allresult.txt'
Final Results are in testdata_out//Result.abridged.txt and testdata_out//Result.full.txt
```

**Comment by ZijieJin** [comment]
Hi, indxAi! For detecting gene fusions using DNA samples, many other tools are currently available and optimized for DNA data. 
For the test data, please run all samples.

**Comment by AnkitYGeneSeq** [comment]
but why can't we use scFusion tool for the DNA sample, is there any possibility of testing the DNA sample on this tool

Additionally, I have a query concerning the testing of the testdata. Is it mandatory to run all the samples for testing purposes, or would it be acceptable to test only 1 or 2 samples initially?

**Comment by AnkitYGeneSeq** [comment]
It's great to hear that many tools are available for detecting gene fusions using DNA samples. However, I'd like to ask if there's a specific reason why we can't also use the tool you mentioned for DNA sequencing. Is there a specific logic or limitation behind this approach that prevents us from using the tool for DNA sequencing? Understanding the reasoning behind this will help us determine the best approach for analyzing our samples.

**Comment by ZijieJin** [comment]
> but why can't we use scFusion tool for the DNA sample, is there any possibility of testing the DNA sample on this tool
> 
> Additionally, I have a query concerning the testing of the testdata. Is it mandatory to run all the samples for testing purposes, or would it be acceptable to test only 1 or 2 samples initially?

You cannot run only one or two samples, because scFusion was designed for single-cell data. The data distribution is different between DNA sample and RNA sample, so please DO NOT run scFusion on DNA samples.
