### ISSUE TITLE
Prepare command doesn't seem to do anything

### ISSUE THREAD

**Issue by MasayukiNagai** [ZijieJin/scFusion#7]
I'm wondering what the `Prepare` subcommand is supposed to do because it gives me nothing after I run the command as noted in the manual.pdf. Although `Prepare` is defined in scFusion.py on line 26-30, I don't see it anywhere else in the script, unlike the other subcommands (i.e., there is no such line as `if sys.argv[1] == 'Prepare':`). Thank you!

**Comment by ZijieJin** [comment]
Thank you! The bug has been fixed and the command "prepare" has been changed to "Index".
