### ISSUE TITLE
Would it be available on 10X?

### ISSUE THREAD

**Issue by byemypast** [ZijieJin/scFusion#8]
Thank you for your great work!
I am trying to utilize the scFusion in my scRNA data. However, I found the software was developed under the protocol of smart-seq2. I wonder whether it could be used on my 10x-based scRNA data?

Thx,
Junyi

**Comment by ZijieJin** [comment]
Indeed, we developed scFusion for Smart-Seq protocols rather than droplet-based 10X. You can run scFusion on your 10X data, but the performance may be not good. We optimized the model using the dense Smart-Seq data, since 10X data is sparse, many true gene fusions might be missed.

**Comment by byemypast** [comment]
Thanks for your kindly support!
Have a nice day :D
